steps:
- name: 'gcr.io/cloud-builders/go'
  args: ['test', './...']
  env: ['PROJECT_ROOT=github.com/soellman/radiotimemachine']
- name: 'gcr.io/cloud-builders/go'
  args: ['build', '-a', '-tags', 'netgo', '-installsuffix', 'netgo', '-o', 'radiotimemachine-linux']
  env: [
         'PROJECT_ROOT=github.com/soellman/radiotimemachine',
         'CGO_ENABLED=0',
         'GOOS=linux'
       ]
- name: 'gcr.io/cloud-builders/docker'
  args: [
          'build',
          '--cache-from', 'gcr.io/$PROJECT_ID/radiotimemachine:latest',
          '-t', 'gcr.io/$PROJECT_ID/radiotimemachine:$SHORT_SHA',
          '-t', 'gcr.io/$PROJECT_ID/radiotimemachine:latest',
          '.'
        ]
images: ['gcr.io/$PROJECT_ID/radiotimemachine']

